ISSUE_TEMPLATE.md

what else should we include here?
related to #73; perhaps we can move some content from there to here.

draft ISSUE TEMPLATE

---

scripts/FLIR/GetFLIR.m
scripts/NDVI/GetNDVI.m
scripts/NDVI/PlotNDVI.m
scripts/PS2/GetPS2.m

Octave scripts on the control PC such that operators on site can view raw data (Vis, FLIR, PS2, Sensors) and make simple analyses and visualizations
First step in pipeline to convert binary files for these sensors to image files.

added matlab/octave scripts for processing PS2, NDVI, FLIR re issue #64

---

scripts/plantcv/PlantcvClowderIndoorAnalysis.py
scripts/plantcv/PlantcvClowderUploader.py

This pull request adds/updates a script that will be run by a Clowder extractor. The script will analyze images that are stored in Clowder from the Danforth Center LemnaTec system using PlantCV. Results per image are posted back to Clowder as metadata. A summary traits file (CSV) is also posted back to Clowder.
With an appropriate Clowder extractor, the code in this pull request will enable us to automate PlantCV analysis. This does not completely close, but is related to issues #31, #33, #36, and #68.
I have tested the code manually on individual Clowder Datasets. More testing will need to be done to integrate the code with an extractor.

Plantcv clowder extractor

---

scripts/gantrymonitor/config_default.json
scripts/gantrymonitor/gantry_monitor_service.py

This merges in several updates to support the new MAC climate weather data. Will also make files immutable on gantry after symlink creation.

Support climate logs

---

scripts/plantcv/PlantcvClowderIndoorAnalysis.py
scripts/plantcv/extractor/config.py
scripts/plantcv/extractor/terra.plantcv.py

This adds config to PCV extractor with a BETYdb URL and key.
If given, the avg_traits.csv file will be uploaded to that BETY instance on creation.

Add BETYdb upload to PlantCV extractor

---

scripts/globusmonitor/globus_monitor_service.py
scripts/globusmonitor/migrateJsonToPostgres.py

Instead of creating many JSON files, write active/pending/completed Globus logs to a Postgres database as well as the mapping of dataset name: Clowder ID.
This should make backup and system scans much faster without the 70,000 tiny json files to walk through, and makes retrieval/operations on these logs easier.

Log Roger Globus monitor into postgres

---

scripts/gantrymonitor/gantry_monitor_service.py
scripts/globusmonitor/config_default.json
scripts/globusmonitor/globus_monitor_service.py
scripts/globusmonitor/globus_uploader_service.py
scripts/globusmonitor/globusuploader.service

Split dual-threaded Globus monitor code on ROGER into two separate services for easier administration and more scalability/bulletproofing.

Split globus monitor

---

.github/PULL_REQUEST_TEMPLATE.md

updated pull request tempated

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

For issue template, the biggest addition is the new 'completion criteria'. 
Also tried to make the content more applicable to the TERRA REF team

revised issue template and pull request template following team process review

---

scripts/hyperspectral/hyperspectral_metadata.py
scripts/hyperspectral/hyperspectral_test.py

reformat some dicts and comment out a false positive in [hyperspectral_test.py](../blob/master/scripts/hyperspectral/hyperspectral_test.py) found by @max-zilla and @czender [here](https://github.com/terraref/computing-pipeline/issues/195#issuecomment-271671120)

Comment out a false positive in hyperspectral_test.py

---

scripts/hyperspectral/hyperspectral_calculation.py
scripts/hyperspectral/hyperspectral_metadata.py
scripts/hyperspectral/hyperspectral_test.py

This pull request includes:
1. Fix the error that the [hyperspectral_metadata.py](../blob/master/scripts/hyperspectral/hyperspectral_metadata.py) may falsely report missing file(s).
2. Comment out one test case that is a suspected or potential false positive in [hyperspectral_test.py](../blob/master/scripts/hyperspectral/hyperspectral_test.py).

Fix File-not-found error, Comment out one false positive test case

---

scripts/buildClowderInstance.py
scripts/globusmonitor/globus_uploader_service.py

This adds new logic code to the Globus pipeline (both MAC and Danforth) that will reflect the new collection/dataset hierarchy defined in the Winter 2016 rebuild.
sensor / year / month / <date> / dataset
e.g.
```
collection: VNIR
collection: --VNIR - 2016
collection: ----VNIR - 2016-12
collection: ------VNIR - 2016-12-05
dataset:    --------VNIR - 2016-12-15-12-13-42-1234
collection: EnvironmentLogger
collection: --EnvironmentLogger - 2016
collection: ----EnvironmentLogger - 2016-12
dataset:    ------EnvironmentLogger - 2016-12-05
```

Add new hierarchy logic to pipeline

---

scripts/addPlotsToGeostreams.py

add script to generate geostream plots from a shapefile

Geostreams population

---

scripts/gantrymonitor/globus_manager_service.py

Improves how series are written to InfluxDB for transfer logging. Just deployed this code to MAC to review performance; will merge when everything looks good.

Change how influxDB entries are written

---

scripts/gantrymonitor/gantry_scanner_service.py
scripts/gantrymonitor/globus_manager_service.py
scripts/globusmonitor/config_default.json
scripts/globusmonitor/globus_monitor_service.py
scripts/globusmonitor/globus_uploader_service.py

various changes to improve logging/fix paths/change permissions according to updates on roger VM. small number of corresponding changes on gantry side.

Roger redeploy config updates

---

scripts/globusmonitor/globus_uploader_service.py

Clean metadata before uploading.

Add new cleaning code

---

scripts/globusmonitor/globus_uploader_service.py

This PR fixes #434.  I've modified getNextUnprocessedTask to use a Postgres CTE (common table element) to update the globus_task.status to PENDING when getting the next task.  This should allow us to run parallel globus-uploader processes.
The use of CTE does introduce additional risk of exceptions due to deadlocking. I think I've handled this, but we'll want to monitor the running pods for restarts to see.

Added PENDING status and exception handling

---

scripts/globusmonitor/globus_uploader_service.py

hotfixes to uploader to also retry on 500 and account for hosts missing trailing / for terrautils.

Uploader tweaks

---

extractors/betydb/Dockerfile
extractors/betydb/extractor_info.json
extractors/geostreams/Dockerfile
extractors/geostreams/extractor_info.json
scripts/globusmonitor/Dockerfile_receiver
scripts/globusmonitor/Dockerfile_uploader

_please edit this template before submitting a new pull request_

update geostreams, bety, globus components

---

scripts/MongoCleanup.js

_please edit this template before submitting a new pull request_

improve mongo cleanup script

---

scripts/filecounter/Dockerfile
scripts/filecounter/counts.py
scripts/filecounter/filecounter.py
scripts/filecounter/templates/sensors.html
scripts/filecounter/users.json
scripts/filecounter/utils.py

- adds a resubmitbyseason endpoint with controls for resubmitting missing data
- adjust color scheme
- clean up sensors page

Filecounter updates

---

extractors/compressor/Dockerfile
extractors/compressor/README.md
extractors/compressor/entrypoint.sh
extractors/compressor/terra_compressor.py
extractors/compressor/terra_compressor_queue.py
extractors/plotclipper/terra_plotclipper.py

Add tool for compressing large GeoTIFFs and implement in plotclipper

Compression tool

---

scripts/gantrymonitor/gantry_scanner_service.py

_please edit this template before submitting a new pull request_

Fix a few bugs for multiple globus destinations

---

scripts/gantrymonitor/gantry_scanner_service.py

addresses a bug introduced in multi-endpoint code.

Add temp fix to route PLY files to Level_1

---

scripts/filecounter/config_default.json
scripts/filecounter/counts.py
scripts/filecounter/filecounter.py
scripts/filecounter/templates/sensors.html
scripts/globusmonitor/config_default.json
scripts/globusmonitor/config_logging.json
scripts/globusmonitor/globus_uploader_service.py

_please edit this template before submitting a new pull request_

Add new seasons to filecounter
